### ISSUE TITLE
split of tokio-pty-process

### ISSUE THREAD

**Issue by aep** [pkgw/stund#20]
i'm implementing osx support, and would like to add tests. would it be ok to split this of into a different repo?

**Comment by pkgw** [comment]
Sorry, I never responded to this question. The module is small enough that I am not sure if it's even worth splitting off to add tests — I am certainly happy to merge any PRs to that effect. But by the same token it is not a big deal to split it if there are good reasons to do so that I'm not thinking of.

**Comment by pkgw** [comment]
OSX support has been implemented, and there are some tests now. I'm going to close this, but feel free to reopen if you'd like to continue the discussion about splitting repositories!
